### ISSUE TITLE
Sociability question

### ISSUE THREAD

**Issue by prt459** [etherkit/MorseArduino#1]
Jason, a delectably simple component.  Thanks.  This could elegantly replace my keyer script.  Question about sociability with a VFO controller (or any other) script.  Does timer.run(); return or block? If it blocks there can be nothing else in loop(){} and the script is a keyer only. If it returns loop(){} can do other things between calls to the keyer.  Obviously, other things that finish quickly and don't delay.   

Also, if update() is called less frequently than 1mS I presume the CW still gets sent but the timing is irregular. If you limited CW speed to say 10wpm can you reduce the update() call frequency?

**Comment by NT7S** [comment]
Admittedly, I made an AVR example sketch using the SimpleTimer component for the reason that it states on the box: it's simple. I didn't dig into the internals of the timer.run() implementation, so I can't say whether it blocks or not. I would say that if you want better control and certainty over this aspect, then implement a timer with the raw register commands as is done here: https://gist.github.com/NT7S/2b5555aa28622c1b3fcbc4d7c74ad926

The whole point of the library is to be hardware agnostic, which shifts the burden of providing the timing to the end user. Examples are provided to give an idea of how things work, but they are certainly not meant to be the ultimate example of how to do things.

The internals of the library assume 1 ms clock ticks, so yes calling _update()_ at a different rate will change the sending speed by a corresponding factor. I'd think reducing the update frequency by very much could make for some poor sounding Morse code, but I haven't tested that hypothesis.

**Comment by prt459** [comment]
I tried it out, not with SimpleTimer, but with a 1mS delay(), on a Nano, and it worked a treat!  This allows loop() to do other things, as long as they complete quickly.  The accuracy of delay() at 1mS could be questioned, but pragmatically, the CW sounds fine.  Thanks Jason.
