### ISSUE TITLE
etherkit.com does no longer exist?

### ISSUE THREAD

**Issue by edegraaff** [etherkit/MorseArduino#7]
Hi, in the documentation etherkit.com is mentioned. Seems the site is no longer active. 
Never the less, the librarys are still valuable for the HAM's so please keep them supported. 

They are used for several projects like the HAB's and WSPR on arduino and esp32 experiments.

Regards

Eelco de PD1EG

**Comment by NT7S** [comment]
I had to close Etherkit during the pandemic but I'm working on bringing it back in the near future. I want to support my code as much as possible, but I'm only one person and I'm working a job plus trying to relaunch my business, so adjust expectations accordingly.

Glad you find the libraries useful and thank you.
Jason NT7S
